
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from text import Text_Frame
from hsh import Hash_Frame
from fcrypt import Fcrypt_Frame

def destroy(window,frame = int):
    """
    \nInput:
    \n\twindow: a tkinter windows instinct
    \n\tframe: int (used to call a build function that creates the windows for a given frame)
    \n## Frames:
    \n\t Menu: 1
    \n\t Strings: 2
    \n\t Hash: 3
    \n\t Fcrypt: 4
    \n### Output
    \n\tRemoves all the children and calls another build function for creating the specified frame

    """
    for i in window.winfo_children():
        i.destroy()
    
    if frame == 1:
        Menu_Frame(window)
    if frame == 2:
        Text_Frame(window)
    if frame == 3:
        Hash_Frame(window)
    if frame == 4:
        Fcrypt_Frame(window)

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\krish\OneDrive\UseFullPrograms\Toolkit\Test GUI\build\assets\frame1")

print(OUTPUT_PATH)
print(ASSETS_PATH)

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def Menu_Frame(window):

    canvas = Canvas(

        window,
        bg = "#053B50",
        height = 813,
        width = 1445,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_text(
        453.0,
        7.0,
        anchor="nw",
        text="ToolKit",
        fill="#EEEEEE",
        font=("JetBrainsMonoRoman ExtraBold", 128 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: destroy(window,2),
        relief="flat"
    )
    button_1.place(
        x=454.0,
        y=182.0,
        width=536.3670654296875,
        height=105.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=454.0,
        y=337.0,
        width=536.3670654296875,
        height=105.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=454.0,
        y=491.0,
        width=536.3670654296875,
        height=105.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=454.0,
        y=628.0,
        width=536.3670654296875,
        height=105.0
    )

    window.mainloop()



window = Tk()

window.geometry("1445x813")
window.configure(bg = "#053B50")

Menu_Frame(window)